/*
 * This source file was generated by the Gradle 'init' task
 */

//Author: Daisy Nolasco and 
//Date : 06/04/25
//purpose: 
package lab7;

import java.util.Scanner;



import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;

public class Huffman {



    public static void main(String[] args) throws FileNotFoundException{

        
        //scannner opens input file given by command line 
        Scanner scanner = new Scanner(new File(args[0]));
      
        
   
    }
    
}